export function Methodology() {
  return (
    <div className="max-w-4xl mx-auto py-20 px-6">
      <h1 className="font-heading text-4xl text-fg mb-8">Our Methodology</h1>
      <div className="prose prose-invert max-w-none text-fg/80 space-y-6">
        <p>
          At GenQ Analytics, we believe in providing absolute precision and uncompromising data privacy.
          Our methodology relies on advanced localized Large Language Models (LLMs) to ensure your data 
          never leaves your secure environment.
        </p>
        
        <h2 className="font-heading text-2xl text-fg mt-8 mb-4">1. Localized Processing</h2>
        <p>
          Unlike cloud-based AI tools, GenQ Analytics processes all CSV uploads and data analysis entirely on your local infrastructure.
          We use optimized, open-weight LLMs specifically tuned for data extraction, aggregation, and synthesis.
        </p>

        <h2 className="font-heading text-2xl text-fg mt-8 mb-4">2. Semantic Synthesis</h2>
        <p>
          Our algorithms parse raw tabular data to identify trends, anomalies, and correlations. By combining 
          deterministic statistical calculations with semantic interpretation, we generate human-readable insights 
          that highlight the "why" behind your metrics.
        </p>

        <h2 className="font-heading text-2xl text-fg mt-8 mb-4">3. Confidence Scoring</h2>
        <p>
          Every insight generated by GenQ Analytics comes with an AI Confidence Score. This metric evaluates 
          the statistical significance of the underlying data points, ensuring you always know how heavily 
          you can rely on a specific conclusion.
        </p>
      </div>
    </div>
  );
}
