import React from 'react';
import { motion } from 'framer-motion';

export function TermsOfService() {
  return (
    <div className="max-w-[800px] mx-auto py-20 px-6 font-body text-fg">
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-8">
        <h1 className="font-heading text-[40px] font-bold">Terms of Service</h1>
        <p className="text-fg/60">Effective Date: April 30, 2026</p>
        
        <div className="space-y-6 text-[15px] leading-relaxed text-fg/80">
          <section className="space-y-3">
            <h2 className="text-[20px] font-semibold text-fg">1. License</h2>
            <p>GenQ Analytics is provided under the GNU General Public License (GPL). You are free to use, modify, and distribute the software in accordance with the license terms.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[20px] font-semibold text-fg">2. Disclaimer</h2>
            <p>The insights and reports generated by GenQ Analytics are for informational purposes only. While we strive for absolute precision, results are generated by AI and should be verified by human experts before making critical business decisions.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[20px] font-semibold text-fg">3. Limitations</h2>
            <p>GenQ Analytics is provided "as is" without warranty of any kind. We are not liable for any damages arising from the use or inability to use our software.</p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
