import base64
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from app.db import reports_db
from app.api.chart_builder import build_charts
from app.api.export_pdf import generate_pdf_response
from app.api.export_docx import generate_docx_response
from app.api.export_notebook import generate_notebook_response

router = APIRouter()

@router.get("/export/{report_id}")
@router.get("/export/{report_id}/pdf")
async def export_pdf(report_id: str):
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")

    report_data = reports_db[report_id]
    return generate_pdf_response(report_id, report_data)

@router.get("/export/{report_id}/docx")
async def export_docx(report_id: str):
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")

    report_data = reports_db[report_id]
    return generate_docx_response(report_id, report_data)

@router.get("/export/{report_id}/notebook")
async def export_notebook(report_id: str):
    """
    Returns an executed Jupyter notebook (.ipynb) reconstructed from the
    stored report — no LLM re-execution required.
    """
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")

    report_data = reports_db[report_id]
    return generate_notebook_response(report_id, report_data)


@router.get("/export/{report_id}/pptx")
async def export_pptx(report_id: str):
    """
    Returns a PowerPoint (.pptx) presentation generated by the Presentation Builder Agent.
    If no PPTX was stored during the pipeline run, generates a basic outline on-the-fly.
    """
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")

    report_data = reports_db[report_id]
    report = report_data.get("report", {})
    filename = report_data.get("filename", "report").replace(".csv", "").replace(".xlsx", "")

    # Try to retrieve stored PPTX from the pipeline
    pptx_bytes = None

    # Check if presentation_results has pptx_bytes stored in the job state
    # (It's not in reports_db, it would be in-memory only at pipeline time)
    # So we always generate fresh from the outline
    presentation_outline = report.get("presentation_outline", {})

    if presentation_outline and presentation_outline.get("slides"):
        pptx_bytes = _generate_pptx_from_outline(presentation_outline, report)
    else:
        # Generate a basic outline on-the-fly
        pptx_bytes = _generate_basic_pptx(report, filename)

    if not pptx_bytes:
        raise HTTPException(status_code=500, detail="Failed to generate PowerPoint presentation")

    safe_name = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in filename)
    return Response(
        content=pptx_bytes,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}_report.pptx"'}
    )


def _generate_pptx_from_outline(outline: dict, report: dict) -> bytes:
    """Build a styled PPTX from a presentation outline dict."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        import io

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        DARK_BG = RGBColor(0x0F, 0x17, 0x2A)
        ACCENT = RGBColor(0x38, 0xBD, 0xF8)
        WHITE = RGBColor(0xFF, 0xFF, 0xFF)
        LIGHT_GRAY = RGBColor(0xCB, 0xD5, 0xE1)
        blank_layout = prs.slide_layouts[6]

        def add_text(slide, text, left, top, width, height, size, color, bold=False, wrap=True):
            tb = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
            tf = tb.text_frame
            tf.word_wrap = wrap
            p = tf.paragraphs[0]
            p.text = str(text)
            if p.runs:
                r = p.runs[0]
                r.font.size = Pt(size)
                r.font.color.rgb = color
                r.font.bold = bold
            return tb

        for slide_def in outline.get("slides", []):
            slide = prs.slides.add_slide(blank_layout)
            bg = slide.background.fill
            bg.solid()
            bg.fore_color.rgb = DARK_BG

            # Accent bar
            bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.08))
            bar.fill.solid()
            bar.fill.fore_color.rgb = ACCENT
            bar.line.fill.background()

            slide_type = slide_def.get("slide_type", "finding")
            title_txt = slide_def.get("title", "")
            headline = slide_def.get("headline", "")
            bullets = slide_def.get("bullets", [])
            notes_txt = slide_def.get("speaker_notes", "")

            if slide_type == "title":
                add_text(slide, outline.get("title", "Analysis Report"),
                         1.5, 2.2, 10, 1.5, 40, WHITE, bold=True)
                add_text(slide, outline.get("subtitle", ""),
                         1.5, 3.9, 10, 0.6, 18, ACCENT)
            else:
                add_text(slide, title_txt, 0.5, 0.2, 12, 0.6, 13, ACCENT, bold=True)
                add_text(slide, headline, 0.5, 1.0, 12, 1.0, 21, WHITE, bold=True)

                if bullets:
                    btb = slide.shapes.add_textbox(Inches(0.7), Inches(2.3), Inches(11), Inches(4.5))
                    btf = btb.text_frame
                    btf.word_wrap = True
                    for i, b in enumerate(bullets[:6]):
                        bp = btf.add_paragraph() if i > 0 else btf.paragraphs[0]
                        bp.text = f"\u2022 {b}"
                        if bp.runs:
                            bp.runs[0].font.size = Pt(16)
                            bp.runs[0].font.color.rgb = LIGHT_GRAY
                        bp.space_before = Pt(8)

            if notes_txt:
                notes_tf = slide.notes_slide.notes_text_frame
                notes_tf.text = notes_txt

        buf = io.BytesIO()
        prs.save(buf)
        buf.seek(0)
        return buf.read()
    except Exception as e:
        import logging
        logging.getLogger("genq_api").error(f"PPTX generation from outline failed: {e}")
        return _generate_basic_pptx(report, "Report")


def _generate_basic_pptx(report: dict, filename: str) -> bytes:
    """Generates a basic fallback PPTX from the report data."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        import io

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        DARK_BG = RGBColor(0x0F, 0x17, 0x2A)
        ACCENT = RGBColor(0x38, 0xBD, 0xF8)
        WHITE = RGBColor(0xFF, 0xFF, 0xFF)
        LIGHT_GRAY = RGBColor(0xCB, 0xD5, 0xE1)
        blank = prs.slide_layouts[6]

        def make_slide(title_text, body_text, headline=""):
            sl = prs.slides.add_slide(blank)
            bg = sl.background.fill
            bg.solid()
            bg.fore_color.rgb = DARK_BG
            bar = sl.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.08))
            bar.fill.solid()
            bar.fill.fore_color.rgb = ACCENT
            bar.line.fill.background()

            tb = sl.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(12), Inches(0.6))
            tb.text_frame.text = str(title_text)
            if tb.text_frame.paragraphs[0].runs:
                r = tb.text_frame.paragraphs[0].runs[0]
                r.font.size = Pt(13)
                r.font.color.rgb = ACCENT
                r.font.bold = True

            if headline:
                hl = sl.shapes.add_textbox(Inches(0.5), Inches(1.0), Inches(12), Inches(1.0))
                hl.text_frame.word_wrap = True
                hl.text_frame.text = str(headline)
                if hl.text_frame.paragraphs[0].runs:
                    r2 = hl.text_frame.paragraphs[0].runs[0]
                    r2.font.size = Pt(22)
                    r2.font.color.rgb = WHITE
                    r2.font.bold = True

            body = sl.shapes.add_textbox(Inches(0.7), Inches(2.3) if headline else Inches(1.2), Inches(11.5), Inches(4.5))
            body.text_frame.word_wrap = True
            body.text_frame.text = str(body_text)[:600]
            if body.text_frame.paragraphs[0].runs:
                r3 = body.text_frame.paragraphs[0].runs[0]
                r3.font.size = Pt(15)
                r3.font.color.rgb = LIGHT_GRAY

        # Title slide
        make_slide(
            report.get("title", f"{filename} — Analytical Report"),
            report.get("domain", "Data Analysis"),
            headline=report.get("executive_headline", "")
        )

        # Executive summary
        exec_summary = report.get("executiveSummary", report.get("executive_summary", ""))
        if exec_summary:
            make_slide("Executive Summary", exec_summary[:600], "Key Findings & Strategic Overview")

        # Key findings
        findings = report.get("keyFindings", [])
        for i, f in enumerate(findings[:5], 1):
            title = f.get("title", f"Finding {i}")
            detail = f.get("detail", f.get("finding", f.get("description", "")))
            make_slide(f"Finding {i}", detail[:400], title)

        # Recommendations
        recs = report.get("recommendations", [])
        if recs:
            rec_text = "\n".join([f"\u2022 {r.get('action', str(r))}" for r in recs[:5]])
            make_slide("Recommendations", rec_text, "Priority Actions & Next Steps")

        buf = io.BytesIO()
        prs.save(buf)
        buf.seek(0)
        return buf.read()
    except Exception as e:
        import logging
        logging.getLogger("genq_api").error(f"Basic PPTX generation failed: {e}")
        return b""


@router.get("/charts/{report_id}")
async def get_report_charts(report_id: str):
    """
    Returns all charts for a report as base64-encoded PNG strings.
    Used by the frontend dashboard and report page to display live charts.
    """
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")

    report_data = reports_db[report_id]
    charts = build_charts(report_data)

    result = []
    for ch in charts:
        img_bytes = ch["buf"].read()
        b64 = base64.b64encode(img_bytes).decode("utf-8")
        result.append({
            "title": ch["title"],
            "interpretation": ch["interpretation"],
            "image": f"data:image/png;base64,{b64}"
        })

    return {"charts": result}
