import io
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from fastapi.responses import StreamingResponse

from app.api.chart_builder import build_charts

def _set_cell_background(cell, hex_color):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>')
    tcPr.append(shd)

def _set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        node = OxmlElement(f'w:{m}')
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)

def _add_heading_styled(doc, text, level, accent_color=RGBColor(0x1A, 0x56, 0xDB)):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.keep_with_next = True

    run = p.add_run(text)
    run.font.name = 'Georgia' if level == 1 else 'Arial'
    if level == 1:
        run.font.size = Pt(18)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x11, 0x11, 0x11)
    elif level == 2:
        run.font.size = Pt(13)
        run.font.bold = True
        run.font.color.rgb = accent_color
    else:
        run.font.size = Pt(11)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x11, 0x11, 0x11)
    return p

def generate_docx_response(report_id: str, report_data: dict) -> StreamingResponse:
    ai_report   = report_data.get("report", {})
    stats       = report_data.get("stats", {})
    filename    = report_data.get("filename", "dataset")

    doc = Document()

    # Margins
    for s in doc.sections:
        s.top_margin = Inches(1.0)
        s.bottom_margin = Inches(1.0)
        s.left_margin = Inches(1.0)
        s.right_margin = Inches(1.0)

    # Styling helper variables
    c_accent_rgb = RGBColor(0x1A, 0x56, 0xDB)
    c_dark_hex = "111111"
    c_zebra_hex = "F9FAFB"
    c_alert_hex = "FFF7ED"

    # Configure default text font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'
    font.size = Pt(10)
    font.color.rgb = RGBColor(0x22, 0x22, 0x22)
    style.paragraph_format.line_spacing = 1.25
    style.paragraph_format.space_after = Pt(8)

    # ── Cover Page ─────────────────────────────────────────────────────────────
    for _ in range(6):
        doc.add_paragraph()

    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_title = p_title.add_run("AI Data Analysis Report")
    run_title.font.name = 'Georgia'
    run_title.font.size = Pt(28)
    run_title.font.bold = True
    run_title.font.color.rgb = RGBColor(0x11, 0x11, 0x11)

    p_sub = doc.add_paragraph()
    p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_sub.paragraph_format.space_after = Pt(24)
    run_sub = p_sub.add_run(filename)
    run_sub.font.size = Pt(13)
    run_sub.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    if ai_report.get("domain"):
        p_dom = doc.add_paragraph()
        p_dom.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_dom.paragraph_format.space_after = Pt(24)
        run_dom = p_dom.add_run(f"Domain: {ai_report['domain']}")
        run_dom.font.size = Pt(11)
        run_dom.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    # Quality Badge Metadata
    shape = stats.get("shape", {})
    dq = stats.get("data_quality", {}) or ai_report.get("_meta", {}).get("dataQuality", {})
    quality_score = dq.get("score", "?")
    quality_grade = dq.get("grade", "?")

    rows_val = shape.get("rows")
    if isinstance(rows_val, (int, float)):
        rows_str = f"{rows_val:,}"
    else:
        rows_str = str(rows_val) if rows_val is not None else "?"
    cols_val = shape.get("columns")
    cols_str = str(cols_val) if cols_val is not None else "?"

    p_meta = doc.add_paragraph()
    p_meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_meta = p_meta.add_run(
        f"{rows_str} rows  ×  {cols_str} columns  |  "
        f"Data Quality: {quality_grade} ({quality_score}/100)"
    )
    run_meta.font.size = Pt(10)
    run_meta.font.bold = True
    run_meta.font.color.rgb = c_accent_rgb

    # Footer style line
    p_foot = doc.add_paragraph()
    p_foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_foot.paragraph_format.space_before = Pt(100)
    run_foot = p_foot.add_run("Generated by GenQ Analytics")
    run_foot.font.size = Pt(9)
    run_foot.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)

    doc.add_page_break()

    # ── 1. Methodology & Data Quality ───────────────────────────────────────────
    _add_heading_styled(doc, "1. Methodology & Data Quality", 1)

    if dq and dq.get("score") is not None:
        _add_heading_styled(doc, "Data Quality Assessment", 2, c_accent_rgb)

        dq_rows = [
            ["Dimension", "Score", "Out of", "Description"],
            ["Completeness", f"{dq.get('completeness', 0):.1f}", "40", "Non-null cell ratio across all columns"],
            ["Consistency", f"{dq.get('consistency', 0):.1f}", "35", "Penalises columns with >5% statistical outliers"],
            ["Structure", f"{dq.get('structure', 0):.1f}", "25", "Well-typed categorical columns with useful cardinality"],
            [f"Total  [Grade: {quality_grade}]", f"{quality_score}", "100", ""],
        ]

        table = doc.add_table(rows=len(dq_rows), cols=4)
        table.autofit = False

        for i, row in enumerate(table.rows):
            row.cells[0].width = Inches(1.8)
            row.cells[1].width = Inches(0.8)
            row.cells[2].width = Inches(0.8)
            row.cells[3].width = Inches(3.1)

            for j, cell in enumerate(row.cells):
                cell.text = dq_rows[i][j]
                _set_cell_margins(cell, top=80, bottom=80, left=100, right=100)

                for paragraph in cell.paragraphs:
                    paragraph.paragraph_format.space_after = Pt(0)
                    for run in paragraph.runs:
                        run.font.size = Pt(9)
                        if i == 0:
                            run.font.bold = True
                            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                        elif i == len(dq_rows) - 1:
                            run.font.bold = True
                            run.font.color.rgb = RGBColor(0x11, 0x11, 0x11)
                        else:
                            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

                if i == 0:
                     _set_cell_background(cell, c_dark_hex)
                elif i == len(dq_rows) - 1:
                     _set_cell_background(cell, "EFF6FF")
                elif i % 2 == 1:
                     _set_cell_background(cell, c_zebra_hex)

        doc.add_paragraph()

    # Methodology section
    _add_heading_styled(doc, "Analysis Methodology", 2, c_accent_rgb)
    sampling_meta = stats.get("sampling", {}) or ai_report.get("_meta", {}).get("sampling", {})
    was_sampled = sampling_meta.get("wasDownsampled", False)
    sample_size_val = sampling_meta.get("sampleSize", shape.get("rows", "?"))
    if isinstance(sample_size_val, (int, float)):
        sample_size_str = f"{sample_size_val:,}"
    else:
        sample_size_str = str(sample_size_val) if sample_size_val is not None else "?"

    full_count_val = sampling_meta.get("fullRowCount", shape.get("rows", "?"))
    if isinstance(full_count_val, (int, float)):
        full_count_str = f"{full_count_val:,}"
    else:
        full_count_str = str(full_count_val) if full_count_val is not None else "?"

    method = sampling_meta.get("method", "full")

    method_labels = {
        "full": "Full dataset — all rows used for analysis",
        "time_series": "Time-series sampling — most recent 70% + periodic samples from history",
        "stratified": "Stratified sampling — proportional sample preserving class distributions",
        "random": "Random sampling — reproducible random sample (seed=42)",
    }
    method_desc = method_labels.get(method, method)

    if was_sampled:
        methodology_text = (
            f"This dataset contained {full_count_str} rows. "
            f"To ensure timely analysis without sacrificing accuracy, a smart sample of "
            f"{sample_size_str} rows was selected using the {method_desc} strategy. "
            f"All statistics, findings, and visualizations are derived from this representative sample. "
            f"A full-data validation pass was performed to cross-check key findings against the complete dataset."
        )
    else:
        methodology_text = (
            f"This dataset contained {full_count_str} rows — within the full-analysis threshold. "
            f"All statistics, findings, and visualizations are derived from the complete dataset."
        )

    doc.add_paragraph(methodology_text)

    # Validation Warnings
    validation_warnings = ai_report.get("_meta", {}).get("sampling", {}).get("validationWarnings", [])
    if validation_warnings:
        _add_heading_styled(doc, "Full-Data Validation Warnings", 2, c_accent_rgb)
        p_warn_intro = doc.add_paragraph(
            "The following findings showed a >20% deviation between the analysis sample and the full dataset. "
            "Interpret these with additional caution:"
        )
        p_warn_intro.runs[0].font.size = Pt(9.5)

        for w in validation_warnings:
            p_w = doc.add_paragraph()
            p_w.paragraph_format.left_indent = Inches(0.25)

            run_lbl = p_w.add_run(f"{w.get('finding', 'Finding')}: ")
            run_lbl.font.bold = True
            run_lbl.font.size = Pt(9.5)

            run_body = p_w.add_run(
                f"Column '{w.get('column')}' — sample value {w.get('sample_value')}, "
                f"full-data mean {w.get('full_data_value')} ({w.get('deviation_pct')}% deviation)."
            )
            run_body.font.size = Pt(9.5)
            run_body.font.italic = True
            run_body.font.color.rgb = RGBColor(0x9A, 0x34, 0x12)

        doc.add_paragraph()

    # ── 2. Executive Summary ────────────────────────────────────────────────────
    exec_sum = ai_report.get("executiveSummary", "")
    if exec_sum:
        _add_heading_styled(doc, "2. Executive Summary", 1)
        doc.add_paragraph(exec_sum)
        doc.add_paragraph()

    # ── 3. Dataset Statistics ────────────────────────────────────────────────────
    num_summary = stats.get("numeric_summary", {})
    missing = stats.get("missing_values", {})
    if num_summary:
        _add_heading_styled(doc, "3. Dataset Statistics", 1)

        stat_rows = [["Column", "Mean", "Std Dev", "Min", "Max", "Missing"]]
        for col, d in num_summary.items():
            stat_rows.append([
                col[:22],
                f"{(d.get('mean') or 0):.3f}",
                f"{(d.get('std') or 0):.3f}",
                f"{(d.get('min') or 0):.3f}",
                f"{(d.get('max') or 0):.3f}",
                str(missing.get(col, 0))
            ])

        table_s = doc.add_table(rows=len(stat_rows), cols=6)
        table_s.autofit = False

        for i, row in enumerate(table_s.rows):
            row.cells[0].width = Inches(1.9)
            row.cells[1].width = Inches(1.0)
            row.cells[2].width = Inches(1.0)
            row.cells[3].width = Inches(0.9)
            row.cells[4].width = Inches(0.9)
            row.cells[5].width = Inches(0.8)

            for j, cell in enumerate(row.cells):
                cell.text = stat_rows[i][j]
                _set_cell_margins(cell, top=80, bottom=80, left=80, right=80)

                for paragraph in cell.paragraphs:
                    paragraph.paragraph_format.space_after = Pt(0)
                    if j > 0:
                        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    for run in paragraph.runs:
                        run.font.size = Pt(9)
                        if i == 0:
                            run.font.bold = True
                            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                        else:
                            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

                if i == 0:
                    _set_cell_background(cell, c_dark_hex)
                elif i % 2 == 0:
                    _set_cell_background(cell, c_zebra_hex)

        doc.add_paragraph()

    # ── 4. Data Visualizations & Interpretation ───────────────────────────────
    charts = build_charts(report_data)
    if charts:
        _add_heading_styled(doc, "4. Data Visualizations & Interpretation", 1)
        doc.add_paragraph(
            "Each chart below was chosen based on the actual structure of your dataset — "
            "not a generic template. An interpretation paragraph follows every chart "
            "explaining what the data is specifically showing."
        )

        for ch in charts:
            _add_heading_styled(doc, ch["title"], 2, c_accent_rgb)

            try:
                ch["buf"].seek(0)
                doc.add_picture(ch["buf"], width=Inches(5.8))
            except Exception as e:
                p_err = doc.add_paragraph(f"[Chart Image Could Not Be Rendered: {e}]")
                p_err.runs[0].font.color.rgb = RGBColor(0xDC, 0x26, 0x26)

            p_interp = doc.add_paragraph()
            p_interp.paragraph_format.left_indent = Inches(0.25)
            p_interp.paragraph_format.space_before = Pt(6)
            p_interp.paragraph_format.space_after = Pt(14)

            run_lbl = p_interp.add_run("Interpretation: ")
            run_lbl.font.bold = True
            run_lbl.font.size = Pt(9.5)
            run_lbl.font.color.rgb = c_accent_rgb

            run_text = p_interp.add_run(ch["interpretation"])
            run_text.font.size = Pt(9.5)
            run_text.font.italic = True
            run_text.font.color.rgb = RGBColor(0x37, 0x41, 0x51)

            doc.add_paragraph()

    # ── 5. Key Findings ────────────────────────────────────────────────────────
    findings = ai_report.get("keyFindings", [])
    if findings:
        _add_heading_styled(doc, "5. Key Findings", 1)

        for i, f in enumerate(findings, 1):
            title_t = f.get("title") or f.get("finding") or f"Finding {i}"
            detail = f.get("detail") or f.get("description") or ""
            conf = f.get("confidenceScore") or f.get("confidence") or 0

            p_fh = doc.add_paragraph()
            p_fh.paragraph_format.keep_with_next = True
            run_fh = p_fh.add_run(f"{i}. {title_t}")
            run_fh.font.name = 'Arial'
            run_fh.font.size = Pt(11.5)
            run_fh.font.bold = True
            run_fh.font.color.rgb = RGBColor(0x11, 0x11, 0x11)

            if detail:
                doc.add_paragraph(detail)

            if conf:
                p_c = doc.add_paragraph()
                p_c.paragraph_format.space_after = Pt(12)
                run_c = p_c.add_run(f"AI confidence: {conf}%")
                run_c.font.size = Pt(8.5)
                run_c.font.italic = True
                run_c.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

        doc.add_paragraph()

    # ── 6. Anomalies Detected ──────────────────────────────────────────────────
    anomalies_ai = ai_report.get("anomalies", [])
    stat_anomalies = stats.get("statistical_anomalies", [])
    if anomalies_ai or stat_anomalies:
        _add_heading_styled(doc, "6. Anomalies Detected", 1)

        if stat_anomalies:
            _add_heading_styled(doc, "Statistically Flagged Columns (Z-score > 3σ)", 2, c_accent_rgb)

            tdata = [["Column", "Outlier Rows", "Column Mean"]]
            for a in stat_anomalies:
                tdata.append([
                    a.get("column", ""),
                    str(a.get("outlier_count", "")),
                    f"{a.get('mean', 0):.4f}"
                ])

            table_a = doc.add_table(rows=len(tdata), cols=3)
            table_a.autofit = False

            for i, row in enumerate(table_a.rows):
                row.cells[0].width = Inches(2.2)
                row.cells[1].width = Inches(1.8)
                row.cells[2].width = Inches(2.5)

                for j, cell in enumerate(row.cells):
                    cell.text = tdata[i][j]
                    _set_cell_margins(cell, top=80, bottom=80, left=80, right=80)

                    for paragraph in cell.paragraphs:
                        paragraph.paragraph_format.space_after = Pt(0)
                        if j > 0:
                            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                        for run in paragraph.runs:
                            run.font.size = Pt(9)
                            if i == 0:
                                run.font.bold = True
                                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                            else:
                                run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

                    if i == 0:
                        _set_cell_background(cell, c_dark_hex)
                    elif i % 2 == 1:
                        _set_cell_background(cell, c_alert_hex)

            doc.add_paragraph()

        if anomalies_ai:
            for a in anomalies_ai:
                sev = str(a.get("severity", "medium")).upper()
                desc = a.get("description", "")
                impact = a.get("businessImpact", "")

                p_ah = doc.add_paragraph()
                p_ah.paragraph_format.keep_with_next = True
                run_ah = p_ah.add_run(f"{a.get('column', 'Unknown')} [{sev}]")
                run_ah.font.bold = True
                run_ah.font.size = Pt(11)

                if desc:
                    doc.add_paragraph(desc)
                if impact:
                    p_i = doc.add_paragraph()
                    p_i.paragraph_format.space_after = Pt(10)
                    run_i = p_i.add_run(f"Business impact: {impact}")
                    run_i.font.size = Pt(9)
                    run_i.font.color.rgb = c_accent_rgb

            doc.add_paragraph()

    # ── 7. Recommendations ────────────────────────────────────────────────────
    recs = ai_report.get("recommendations", [])
    if recs:
        _add_heading_styled(doc, "7. Recommendations", 1)

        for i, rec in enumerate(recs, 1):
            priority = str(rec.get("priority", "Medium")).upper()
            action = rec.get("action", "")
            rationale = rec.get("rationale", "")

            p_rh = doc.add_paragraph()
            p_rh.paragraph_format.keep_with_next = True

            run_num = p_rh.add_run(f"{i}. ")
            run_num.font.bold = True

            run_act = p_rh.add_run(action)
            run_act.font.bold = True

            run_pri = p_rh.add_run(f" [{priority}]")
            run_pri.font.bold = True
            run_pri.font.color.rgb = c_accent_rgb

            if rationale:
                doc.add_paragraph(rationale)

        doc.add_paragraph()

    # Save to BytesIO buffer
    bio = io.BytesIO()
    doc.save(bio)
    bio.seek(0)

    clean_filename = filename.replace(" ", "_").replace("/", "_").replace("\\", "_")
    return StreamingResponse(
        bio,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={clean_filename}_Report.docx"}
    )
